parameters:
  -
    name: name
    type: string
    label: Application Name
    description: Name of the application configuration.
    required: true
  -
    name: ip
    type: ipaddress
    label: Application Virtual IP (VIP)
    description: Application VIP that the clients access.
    required: true
  -
    name: lb-alg
    type: string
    label: LoadBalancing Algorithm 
    description: Choose the load balancing method for LB client requests.
    allowed-values:   
        - ROUNDROBIN
        - LEASTCONNECTION
    default: ROUNDROBIN
  -
    name: svc-servers                            
    type: object[]                               
    label: Application Server IPs                
    description: Backend host Server IPs         
    required: true                               
    parameters:                                  
      - 
        name: ip                                 
        label: IP Address of the Server          
        description: IP Address of the Server    
        type: ipaddress                          
        required: true                           
      - 
        name: svc-name                           
        label: Name of the service               
        description: Name of the service         
        type: string                             
        required: true                           
  -
    name: svc-port                               
    type: tcp-port                               
    label: Service Port                          
    description: TCP port of back-end service    
    default: 80                                  